### ISSUE TITLE
Error loading images, webms, and threads similar to #70 and #92

### ISSUE THREAD

**Issue by steald** [Floens/Clover#469] opened 2018-04-27 18:05 UTC
[short and descriptive title]
Images and webms do not load 
[detailed explanation of the issue]
After images having super slow load times on 1.2.3 i decided to finally update clover. But now images wont loads at all. Ill boot up the app to /b/ and the images will stay blank and eventually show an error message inplace of images. Ill swap around boards and almost randomly get some images to load. But when i click on the threadsand swipe through them the images will start to fail to load. And when i press back to leave gallery mode it will show the a low res version of the op image and the app will softlock where no buttons work besides the home button to exit. Ive tried disabling https like was suggested in #70 and #92 but nothing changed. I first thought my new internet upgrade might be the problem like they are throttling me or something. But i have the same problem on data aswell. Installing 2.3.0 or 2.2.0 didnt change anything and i get an error when trying to reinstall 1.2.3
[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]6.0
Phone model: [Find at Settings > About phone > Model number]LG-h812 (LG G4)
Clover version: [Find at the bottom of the settings screen of Clover]2.3.1

**Comment by Floens** [comment] 2018-04-27 18:06
Duplicate of #467

**Closed by Floens** 2018-04-27 18:06 UTC
