### ISSUE TITLE
Request: Default Post Option

### ISSUE THREAD

**Issue by lehitoskin** [Floens/Clover#489] opened 2018-05-07 01:17 UTC
It'd be handy to have a way to make every post use a default option, say, `since4pass`. I don't know how this could be done generically for use with sites other than 4chan, but I think it'd be useful.

**Comment by Floens** [comment] 2018-05-07 08:33
There could be an option below the default name option that does the same but for the Options field.

**Comment by Floens** [comment] 2018-07-04 21:51
Closing as a duplicate of #504
This issue was first but the other one has an extra suggestion.

**Closed by Floens** 2018-07-04 21:51 UTC
Labels: feature, good first issue
