### ISSUE TITLE
Nexus5x Android O - Clover freezes and eventually crashes after viewing replies to a post

### ISSUE THREAD

**Issue by zachwulf** [Floens/Clover#364] opened 2017-10-18 17:05 UTC
When browsing a thread and the replies to a post are clicked, opening the modal, upon closing that modal all input no longer works except for the back button. The app will eventually crash if you tap around enough.

Steps to Reproduce:
1. Nexus5x, running Android O
2. Open Clover, select any thread
3. Select the "X Replies" button at the bottom of any post to open the replies modal window
4. Hit back or close the modal replies window
5. No touch inputs are recognized at this point, app will eventually force close.
6. This is very consistent, happening 100% of the time for me. Should be easy to reproduce.

Android version: 8.0.0
Phone model: Nexus5x
Clover version: 2.3.1

**Comment by Floens** [comment] 2017-10-18 17:59
Does this have to do with #360 ?

**Comment by zachwulf** [comment] 2017-10-18 18:31
Looks like it does, I also had animations disabled. I just re-enabled them and I can browse fine after closing the modals without issue. 

Any estimate on when the next version is scheduled for? I'll leave animations on for now.

**Comment by Androiddude101101** [comment] 2017-11-03 21:57
S8 here just updated to oreo. Same exact problem. Animations on fixes it

**Comment by Floens** [comment] 2017-11-08 19:21
Duplicate of #360

**Closed by Floens** 2017-11-08 19:21 UTC
