### ISSUE TITLE
Can't add any boards other than the defaults.

### ISSUE THREAD

**Issue by dar-irl** [Floens/Clover#241] opened 2016-10-05 21:12 UTC
Just reinstalled clover, and whenever I try to add other boards it gives me an "unknown board code" error.

Android version: 6.0.1
Phone model: Xperia Z3 Compact D5803
Clover version: 2.1.3

**Comment by Floens** [comment] 2016-10-05 21:12
Duplicate of #234

**Closed by Floens** 2016-10-05 21:12 UTC
