### ISSUE TITLE
"Unknown Board Code"

### ISSUE THREAD

**Issue by Mikaphewn** [Floens/Clover#238] opened 2016-10-04 21:25 UTC
[detailed explanation of the issue]
I can not add any boards. If I add any, I get the "Unknown Board Code" error. I've tried vp and /vp/. This started happening recently when I cleared data. I've tried uninstalling and reinstalling, it didn't work 

Android version: 6.0.1

Phone model: SM-G550T1

Clover version: v2.1.3

**Comment by Floens** [comment] 2016-10-04 21:26
Duplicate of #234

**Closed by Floens** 2016-10-04 21:26 UTC
