### ISSUE TITLE
Capcha not loading twice

### ISSUE THREAD

**Issue by SashKhe** [Floens/Clover#63] opened 2015-04-07 18:44 UTC
HTC Desire 500 w/ Android 4.1.2
Clover 1.2.10
Capcha loading fine the first time before replying, but it just keeps  "Loading capcha..." on the second and subsequent tries seemingly indefinitely.

If I clean the cache it works once more, but I need to repeat this for every reply.

**Comment by Floens** [comment] 2015-04-07 18:45
Can you take a look at logcat to see if the webview produces an error?

**Comment by SashKhe** [comment] 2015-04-07 18:53
If you can explain me how to do that from an actual phone, I'll be glad to, otherwise it'll have to wait until I get home and emulate

**Comment by Floens** [comment] 2015-04-07 19:11
You can use an app like catlog to read the log on the device itself https://play.google.com/store/apps/details?id=com.nolanlawson.logcat
It does need root though.
Otherwise you'll need `adb logcat`

**Comment by Floens** [comment] 2015-04-10 14:10
Can you still check the log for me?

**Comment by ait3** [comment] 2015-04-14 19:12
sorry, after 2 hours of screwing around, googling many things and downloading a 10gb filed throttled down to 10kb/s i can't get it to work

**Comment by SashKhe** [comment] 2015-04-14 19:19
Sorry for being a fuckup, I got home yesterday, and I can't get the damn emulator working, I'll root my phone and get back to you with the logs

**Comment by Floens** [comment] 2015-04-14 20:17
You can see the log with adb on a computer, no root required

**Comment by ait3** [comment] 2015-04-14 22:38
i know, but it is not detecting my phone, and i am too tired to try and fix it right now

**Comment by Minjaman10** [comment] 2015-04-16 06:27
You commented on my review a couple days ago regarding this issue. I can't give you a log atm because I just bricked my phone, but will definitely contribute as best I can if I can repair it.

**Comment by DemetriussXVII** [comment] 2015-04-18 09:22
I've the same issue. Galaxy S II running Cyanogen Mod 11 android 4.2.2

**Comment by SashKhe** [comment] 2015-04-18 22:49
@Floens I wish I got an email of your last reply beforehand, would've spared me the pain of fumbling with rooting. Alas, here are the logs, stripped only to include any and all lines with the Clover pid, with cleared cache (no problems) and after posting a comment once already (capcha keeps loading).

I started logcat, started Clover, got to a thread, hit reply, made a post, solved capcha, went back to the main page and refreshed.
Except with the uncleared cache I didn't actually post the reply, and went back to the main page after letting it load for a few seconds.

http://pastebin.com/vuyn6mAZ - Clean Cache
http://pastebin.com/zZKupH6t - Corrupt Cache

Thanks for working on it!

**Comment by Floens** [comment] 2015-04-21 15:44
Hm, it seems that HTC has its own javascript for webview. I'll add some debug stuff for javascript to check if there are js errors.

**Comment by Floens** [comment] 2015-04-22 15:15
Is this actually an issue for you in Chanu or other chan apps?

**Comment by DemetriussXVII** [comment] 2015-04-22 15:19
I've only tried this App so far and I like it very much that I wouldn't want to try another.

**Comment by Floens** [comment] 2015-04-22 15:31
I can check the source code of these apps if they don't have this issue.

**Comment by DemetriussXVII** [comment] 2015-04-22 15:32
Do you recommend a one for me to try or I should look for a one?

**Comment by Floens** [comment] 2015-04-22 15:34
https://f-droid.org/repository/browse/?fdid=com.chanapps.four.activity

**Comment by DemetriussXVII** [comment] 2015-04-22 15:46
works flawlessly.

**Comment by Floens** [comment] 2015-04-22 15:47
Then I might be able to fix it.

**Comment by DemetriussXVII** [comment] 2015-04-22 15:48
Let me know if you need any help.

**Comment by SashKhe** [comment] 2015-04-22 17:49
Chanu captcha also works for me, although it looks and feels positively shitty, regardless

**Comment by Floens** [comment] 2015-04-23 21:20
Does this build work for you?
http://a.pomf.se/egfqeq.apk
(it's signed with the same signature as Clover google play)

**Comment by Accelerando** [comment] 2015-04-25 20:54
I'm having the same problem and the build that you posted to pomf doesn't fix the issue. Although I do get "Loading captcha..." now instead of just a black screen.

**Comment by Floens** [comment] 2015-04-26 16:20
@DemetriussXVII @SashKhe can you take a look at that apk?

**Comment by DemetriussXVII** [comment] 2015-04-26 16:34
Doesn't work at all. In the Google Play build, you can reply/make a thread and the captcha would load once and once only but in this build, it wouldn't load at all, it either shows a blank screen, loading captcha or shows I'm not a robot thing and nothing beyond that. @Floens

**Comment by Floens** [comment] 2015-04-26 17:22
@DemetriussXVII are there any significant errors in the logs? Its doing the exact same thing as Chanu now. It works perfectly on my devices. Otherwise I'm afraid I can't help you.

**Comment by DemetriussXVII** [comment] 2015-04-26 17:35
@Floens Which logs exactly? Chanu worked with no problems whatsoever, I'm afraid that the problem is in Clover since I'm not the only one who faced this issue. Since it's open-source, I'll try to see if I can patch it.

**Comment by Floens** [comment] 2015-04-26 17:35
@DemetriussXVII The adb logs. Good luck!

**Comment by DemetriussXVII** [comment] 2015-04-26 17:39
@Floens Thank you! I'll get back to you if if I fixed it. Do I need Java JDK and JRE as well?

**Comment by Floens** [comment] 2015-04-26 17:40
@DemetriussXVII Take a look at https://github.com/Floens/Clover/wiki/Building-Clover

**Comment by DemetriussXVII** [comment] 2015-04-26 17:43
@Floens All right, thank you.

**Comment by SashKhe** [comment] 2015-04-26 17:50
@Floens Weird, I remember posting a reply when you posted the apk. It doesn't work, still, but it's obvious things had changed. I'll send some data your way in an hour or so, if you're still willing to look into it.

**Comment by Floens** [comment] 2015-04-26 17:50
Yes please!

**Comment by SashKhe** [comment] 2015-04-26 18:59
Here are the logs:
[Clean cache](http://pastebin.com/d3mEBxhU)
[Corrupt cache](http://pastebin.com/VnqA4Fqh)
And I re-uploaded the previous two, because they would eventually expire, so here they are
[clean](http://pastebin.com/CFGFaL77)
[corrupt](http://pastebin.com/CvzazjCL)

I'll root my phone, get to the cache, if it's helpful at all, and get back to you with it too.

**Comment by DemetriussXVII** [comment] 2015-04-26 19:01
@SashKhe My phone is rooted and I've the same issue as you. I can try to pull off the logs and send 'em here if needed.

**Comment by Floens** [comment] 2015-04-26 19:58
Can you try to disable `Use HTTPS` in the advanced settings? (settings > menu > advanced settings)

**Comment by DemetriussXVII** [comment] 2015-04-26 21:19
Nope, doesn't work. I'm going to try Clover tomorrow on my other phone and see what happens. I've an idea, how about you make it so when you post something and reach the captcha, a web page would open for your to enter the captcha and once you enter it correctly, it's get closed or whatever and you return back to the app. @Floens

**Comment by SashKhe** [comment] 2015-04-26 21:40
@Floens Does not fix the main problem, but the weird colorful rectangle turned into a plain white rectangle suspiciously like the background of ReCaptcha.
@DemetriussXVII 
![67b](https://cloud.githubusercontent.com/assets/8193663/7339401/8d6e13ba-ec6d-11e4-8caf-41db8ebf3df9.jpg)
No offense :smile:

**Comment by Floens** [comment] 2015-08-03 20:44
I got my hands on a device with 4.2 and managed to reproduce the bug, and a possible fix. Could you take a look at this build?
https://my.mixtape.moe/xgokli.apk

I signed it with the same signature as Clover on the Play Store, it will be safe if you upgrade an existing app.

**Comment by Reslof** [comment] 2015-08-04 17:22
T-Mobile Galaxy S3 with stock rooted rom with 4.1.2. 
Using the above build made the problem go away. Thanks Floens!

Now if only the captcha image select could be resized to fit the screen instead of having to scroll around...

**Comment by Floens** [comment] 2015-08-06 14:15
Can @SashKhe and @DemetriussXVII please confirm?

**Comment by DemetriussXVII** [comment] 2015-08-07 17:22
@Floens Can you re-upload it to ZippyShare?

**Comment by isc30** [comment] 2015-08-28 23:53
Same problem here: galaxy s3 mini android 4.1.2
Can you reupload last link? Isnt working
Thx!

**Comment by Floens** [comment] 2015-08-29 13:08
The download works fine here.

**Comment by DemetriussXVII** [comment] 2015-10-03 12:42
Updated phone to 4.4.4 . Issue is gone.

**Comment by Floens** [comment] 2016-01-16 23:11
This was fixed by placing the script tag at the bottom of the page, because the script would be loaded immediately the second time because then it's cached, and the captcha callback couldn't be registered because the function wouldn't be available at that stage. Moving it to the bottom fixes it.

**Closed by Floens** 2016-01-16 23:11 UTC
Labels: bug, device bug
