### ISSUE TITLE
Preloading Next Image

### ISSUE THREAD

**Issue by StevenPolley** [Floens/Clover#359] opened 2017-09-21 02:38 UTC
Preloading Next Image

It'd be an improvement if when viewing the album of the thread, the next image or two was downloaded (when on WiFi)  so by the time you scroll it is ready to go.

[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by Floens** [comment] 2017-09-21 12:41
Duplicate of #267

**Closed by Floens** 2017-09-21 12:41 UTC
