### ISSUE TITLE
Viewing Bans in Clover

### ISSUE THREAD

**Issue by Golfavel** [Floens/Clover#363] opened 2017-10-12 22:06 UTC
It is currently not possible to view a ban (and perform its available actions, such as appealing) while in Clover. I suggest being able to view a ban by typing on the warning when it appears after attempting to make a post.

Clover version: 2.3.1

**Comment by Floens** [comment] 2017-12-30 23:58
Duplicate of #231

**Closed by Floens** 2017-12-30 23:58 UTC
