### ISSUE TITLE
Can't save images ("Saving Image Failed")

### ISSUE THREAD

**Issue by mrcareles** [Floens/Clover#212] opened 2016-07-12 23:42 UTC
Attempting to save images results in an error

So basically, whenever I try to save an image a message pops up that says "Saving Image Failed". My save file destination is set to my SD card in a folder named "Pictures". Changing the save destination results in the error popping up again later when u try to save an image. I've never has this issue up until recently and is most unfortunate since pictures I find in ylyl threads will forever be lost to my eyes. Anything my stupid ass is missing? Is this even an issue?

Android version: 5.1.1
Phone model: SM-G360T
Clover version: v2.1.3

**Comment by Floens** [comment] 2016-07-13 12:41
Closing as duplicate of #178

**Closed by Floens** 2016-07-13 12:41 UTC

**Comment by mrcareles** [comment] 2016-07-14 02:52
Alright, well it isn't the same issue but okay. Thanks for "helping" anyway.
