### ISSUE TITLE
Can't rearrange added 'sites' on clover dev

### ISSUE THREAD

**Issue by SugnaB** [Floens/Clover#405] opened 2018-01-28 15:05 UTC
Unable to move added sites up or down 

On the clover dev apk there is no feature to choose what site you want to load first. If you added 8chan instead of 4chsn first there is no way to swap them around meaning, 8chan will always load first. You can rearrange the boards but not the sites

Android version: 7.1.2
Phone model: ZTE Axon 7
Clover version: v2.3.1-3cc3c6a0

**Comment by Floens** [comment] 2018-01-28 15:06
Yes, still has to be implemented, along with site deletion.

**Comment by SugnaB** [comment] 2018-01-28 15:09
'😰😰😰😰

**Comment by Floens** [comment] 2018-02-12 14:21
Closing as a duplicate of #394

**Closed by Floens** 2018-02-12 14:21 UTC
