### ISSUE TITLE
Replies disappear 

### ISSUE THREAD

**Issue by tumblingdown** [Floens/Clover#134] opened 2015-11-28 16:22 UTC
Wierd issue where sometimes half or all the replies in a thread will disappear. This has happened twice; once while trying to reply and once when loading a WebM. Android 5.0 on a Galaxy s5.

**Comment by falsidge** [comment] 2015-11-29 00:33
duplicate of #131

**Comment by Floens** [comment] 2015-11-30 09:06
Yes closing this as a duplicate

**Closed by Floens** 2015-11-30 09:06 UTC
