### ISSUE TITLE
App crashes when removing all boards and then starting the app

### ISSUE THREAD

**Issue by ConstruKction** [Floens/Clover#191] opened 2016-05-17 07:05 UTC
The app crashes when trying to run it after removing all boards, then killing the app, and trying to open it up again.

Android version: 6.0.1 (Unofficial CM13)
Phone model: Xiaomi Mi 5
Clover version: 2.1.3

**Comment by Floens** [comment] 2016-05-17 07:24
There was a check so that you can't remove the last board, but I forgot it when moving to ItemTouchHelper.
I'll add it in again, thanks.

**Comment by Floens** [comment] 2017-09-18 09:50
Apparently there are two issues open about this
Closing as a duplicate of #282

**Closed by Floens** 2017-09-18 09:50 UTC
