### ISSUE TITLE
Watched threads disappear at random

### ISSUE THREAD

**Issue by Ospreyhawk** [Floens/Clover#87] opened 2015-07-06 04:58 UTC
I had copied my old.phone onto a new one (same model) using the Helium app which allowed me to also copy the data from my apps (user name, watched threads, etc.).

This issue I'm talking about did not start until after I had finished syncing everything.

What's been happening is that threads I start watching sometimes disappear from the watch list even though they are still active.  I also witnessed a bug where if you partially drag a watched thread a little bit and release it (sliding tap that happens with the factory screen protector), it will load the thread but be removed from the list.

**Comment by Floens** [comment] 2015-07-26 12:57
Sorry, can't reproduce this issue. If there really was a bug then it's probably fixed in the newer version.

**Closed by Floens** 2015-07-26 12:57 UTC
Labels: cannot reproduce
