### ISSUE TITLE
Clover Refuses to Load Images

### ISSUE THREAD

**Issue by EnzymeSigma** [Floens/Clover#472] opened 2018-04-28 00:37 UTC
About a few days ago after I had upgraded to 2.3.1 Clover began loading images strangely slow, and now it flat out refuses to load images at all even when my internet connection it fine, and I can still read text and enter threads, I haven't tried sending anything yet. I've tried reinstalling a previous version but it gives me a package corruption error. Semi-related; F-Droid has also been giving me an index error after upgrading as well, with the same results when trying to downgrade.

Android version: 7.1.1
Phone model: Moto Z2 Play
Clover version: 2.3.1

**Comment by knasen88** [comment] 2018-04-28 01:38
Same, but my android is 5.0 and HTC one m8

**Comment by knasen88** [comment] 2018-04-28 01:38
Can I rollback app somehow?

**Comment by silentreefer** [comment] 2018-04-28 02:09
I have the same issue on my S8+ Full factory.

**Comment by repkam09** [comment] 2018-04-28 03:41
Same issue here on my OnePlus 5T, Android 8.1.0, Clover v2.3.1 F-Droid.

**Comment by esgwpl** [comment] 2018-04-28 06:57
Use the dev version.

**Comment by Floens** [comment] 2018-04-28 09:04
**Please** look at the other issues before creating new ones.

This is a duplicate of #467. An update is pushed.

**Closed by Floens** 2018-04-28 09:04 UTC
