### ISSUE TITLE
No webm support on gallery app for clover

### ISSUE THREAD

**Issue by Eleandre** [Floens/Clover#345] opened 2017-08-11 12:12 UTC
My Video player couldn't play webm on my default video player for clover app

I installed LineageOS on my phone many days ago and I found out it doesn't have webm support for gallery apps, the browser with updated Google's Web System View can only play webm but It's difficult for me to browse on it because of ads that cannot block.

I only use VLC for android  and enable "Use external video player" to play on it or I use default browser.

Android version: 6.0.1
Phone model: Cherry Mobile Flare J2
Clover version: 2.3.1

**Comment by Floens** [comment] 2017-08-14 13:59
Probably a duplicate of #310

**Closed** 2017-09-18 09:58 UTC
