### ISSUE TITLE
Clover does not let save to an external SD card. Suggestion

### ISSUE THREAD

**Issue by EfronC** [Floens/Clover#369] opened 2017-11-21 08:48 UTC
It's not an unknow issue, #258 and #239 have mentioned the problem. Since Android 4.4, the OS does not let 3rd party apps to write on the SD, unless the app have created the folder during install. This is a common problem, and most of the solutions need to root the device to change the permissions, or to use other apps to move the files from internal, to external storage, which is not recommended since, if the app is unistalled, it will delete the folder where everything is being saved.

I want to make a suggestion: Is it possible to create the Clover media folder since installation, instead of waiting untill you save your first image? This way the problem should be fixed since the folder would have the right permissions in theory. Also, reading a little about the problem, some people recommed for developers to use the "storage access framework", that aparently lets you use the SD like if it was the internal storage.

Just a pair of suggestions to solve this problem, if possible.

Android version: 4.4
Phone model: Lenovo B8000-F
Clover version: 2.3.1

**Comment by Floens** [comment] 2017-11-21 08:52
The issue is #178 
I've never heard of creating a folder on installation, where did you get that from?
And yes, in order to save to the external storage you need to implement the storage framework, as discussed in #178

**Comment by EfronC** [comment] 2017-11-21 08:59
I'm not familiarized with Android programming, and that's why i was asking, since i think some apps does similar things. Sorry, i did not find that discussion since i only searched for SD on the filters, and reading it, i think i will need to wait until is implemented.

**Comment by EfronC** [comment] 2017-11-21 09:15
Sorry to reply again, just wanted to share a little update.

I made a little experiment: I installed Clover 2.1.3 on my external SD(Choose the SD on installation from APK), it created a folder called "org.floens.clover" on Android/data/ on my SD which only contained a folder called cache, inside "org.floens.clover" i created a folder called Clover, and the i went to settings in the app, and changed the default media folder to the one i created on the SD. I tried to save an image, and it was a success, i was a able the save the media on SD. 

If someone find this information helpfull, then you know it works.

**Comment by Xeph20** [comment] 2017-11-22 02:44
How do you install on SD? I don't seem to have that option. I'm on nougat and unable to select external SD

**Comment by EfronC** [comment] 2017-11-22 03:56
Download the Apk, click on it, and it should ask it where to install, on my tablet is a screen like this 
![screenshot_2017-11-21-21-49-28](https://user-images.githubusercontent.com/5926318/33109322-80a8301a-cf06-11e7-8db2-e1ba5bf245ed.png)

Also, i think you should go, in your phone/tablet, to settings/storage, and there should be an option to choose default storage, but i'm not sure if this is for apps.

**Comment by Xeph20** [comment] 2017-11-22 03:59
Thanks for replying but I don't have those options on my phone :s I'm gonna try some apps apps but for them to work I need to format my SD card which I don't want to atm

**Comment by Floens** [comment] 2018-01-25 10:48
Closing as a duplicate of #178

**Closed by Floens** 2018-01-25 10:48 UTC
