### ISSUE TITLE
issue #156 still presist (unknown board code)

### ISSUE THREAD

**Issue by naufalnasiri** [Floens/Clover#240] opened 2016-10-05 14:02 UTC
whenever i tried to add another non-default board, it says that the board code is unknown. The other guy had the issue resolved by itself, but not in my case.  I already tried typing in the board code with and without dashes, and reinstalling the app a couple of times as per your suggestion in the issue 156 thread, but none of it is working.

**Comment by Floens** [comment] 2016-10-05 14:04
Duplicate of #234

**Closed by Floens** 2016-10-05 14:04 UTC
