### ISSUE TITLE
Can't select external memory to save pictures

### ISSUE THREAD

**Issue by DarkTzitzimine** [Floens/Clover#581] opened 2018-10-26 15:46 UTC
I recently installed Clover on a Samsung Galaxy J4 and despite the app being located on the Micro SD, I can only select folders within the phone's internal memory.

Android version: 8.0.0
Phone model: SM-J400M
Clover version: v3.0.1

**Comment by Floens** [comment] 2018-10-31 08:10
Duplicate of https://github.com/Floens/Clover/issues/178

**Closed by Floens** 2018-10-31 08:10 UTC
