### ISSUE TITLE
App crashes when trying to set storage location for downloads

### ISSUE THREAD

**Issue by Tronmech** [Floens/Clover#285] opened 2017-01-31 19:54 UTC
On multiple tablets with SD card support, an attempt to change the storage location for downloads causes the app to FC. 

[detailed explanation of the issue]
See Above. 

[steps to reproduce the issue]
OPEN the app
Select Settings
Select "Save location" 
APP Force closes
Android version:
1) Android 5.0.1
2) Android 6.0.1 (December 1, 2016 security update) 
Phone model:
1) Asus P022 (Zenpad 8 - Z380) 
2) Samsung Galaxy Tab A 10.1 with S Pen (SM-P580) 
Clover version: 2.2.0 and some previous versions.

**Comment by Floens** [comment] 2017-01-31 19:56
Duplicate of #239 
Thank's anyway for confirming the devices where it fails.

**Closed by Floens** 2017-01-31 19:56 UTC
