### ISSUE TITLE
Application restarts when opening it from icon on homescreen

### ISSUE THREAD

**Issue by cosimone64** [Floens/Clover#471] opened 2018-04-27 22:58 UTC
Application restarts when opening it from icon on homescreen

I don't know if this is intended behavior, but every time I leave the application via the home button and then reopen it by touching the icon, it reloads the first board, as if it were started anew. This doesn't happen when switching to it from the "open applications" screen (the one where you can see open applications and close them to free RAM, I don't remember the exact name).
Whether this is intended behavior or not, I'd like to have an option to choose whether to keep the application open on the current board and thread or restart. This did not happen with the F-Droid version (the "state" of the application was preserved), but it does happen with the current stable version from the website.

To reproduce this, simply "park" the application by pressing the home button, then reopen it by clicking on the icon on the homescreen or launcher.

Android version: 7.1.2 N2G47H
Phone model: Xiaomi Redmi 5 Plus
Clover version: 3.0.0, .apk directly downloaded from the website.

**Comment by Floens** [comment] 2018-04-27 23:00
Duplicate of #470 

To fix, keep pressing back until clover is fully closed. Then it should operate normally again.

**Closed by Floens** 2018-04-27 23:00 UTC
