### ISSUE TITLE
Cannot set external memory as save location

### ISSUE THREAD

**Issue by ZalgoNoise** [Floens/Clover#258] opened 2016-11-19 16:21 UTC
[short and descriptive title]

[detailed explanation of the issue]

[steps to reproduce the issue]

Android version: [Find at Settings > About phone > android version]
Phone model: [Find at Settings > About phone > Model number]
Clover version: [Find at the bottom of the settings screen of Clover]

**Comment by Floens** [comment] 2016-11-19 16:22
Duplicate of #239

**Closed by Floens** 2016-11-19 16:22 UTC

**Comment by ZalgoNoise** [comment] 2016-11-19 16:26
Sorry... First time, accidentally pressed next. 

Description:

I am able to save on a different directory other than the default internal SD > Clover. The problem is that I easily stack up space and the internal card is very limited. 

I'd like to suggest the ability to 'folder up' beyond the internal memory in order to set the save location to external memory. 

Running Clover on Android 5.1.1 Lollipop with a Samsung Galaxy J5, full stock except root access.

**Comment by ZalgoNoise** [comment] 2016-11-19 16:27
Apologies and thank you for your work.
