### ISSUE TITLE
Sliding partially sliding from searched catalog causes thread to be searched

### ISSUE THREAD

**Issue by niggsly** [Floens/Clover#136] opened 2015-12-01 03:28 UTC
Using the search function in the catalog, opening a thread, then partially sliding back to the catalog causes the thread to be searched as well, resulting in only the posts that contain the searched phrase to show up. Here's a video of what I'm talking about: https://u.pomf.io/kxixux.mp4

**Comment by Floens** [comment] 2015-12-01 12:38
Closing as duplicate of #131

**Closed by Floens** 2015-12-01 12:38 UTC
