### ISSUE TITLE
"Save original filename" for album

### ISSUE THREAD

**Issue by hardliner5000** [Floens/Clover#186] opened 2016-04-19 22:10 UTC
I just noticed that there's a dysfonction in the "save original filename" in "Download album" choice. In the single image save it works fine but in case of album save, the images are not saved with the original filename. Just random names. Is there a way to fix this issue, please? Thanks.

**Comment by Floens** [comment] 2016-04-20 12:28
Duplicate of #155

**Closed by Floens** 2016-04-20 12:28 UTC
