### ISSUE TITLE
Clover not listed on Google Play.

### ISSUE THREAD

**Issue by SAM-CY** [Floens/Clover#149] opened 2016-01-22 06:39 UTC
I've just noticed that Clover is not on the Google Play store at the moment. Has it been removed? D:

**Comment by Xefir** [comment] 2016-01-22 07:21
Please see the official note on the Clover web site : http://floens.github.io/Clover/gp_unavailable.txt

Basically, we have to wait ...

**Comment by Floens** [comment] 2016-01-26 12:40
I have an update on the appeal. It was denied but they gave me some valuable feedback (or, the issue was just what I thought.)

See as requested in #124 and added in https://github.com/Floens/Clover/commit/22ace00b2166ef41587522bba7f8a3dec9d83e22 I added in two new default boards and shuffled all of them so that /g/ wasn't always at the top. Clover requires hardcoding some boards because otherwise the board list is empty while Clover is waiting for the api response. This is only done when you launch Clover for the first time. So after that update instead of always having the following order: /g/, /v/, /a/, /co/, /int/, it randomized the order of these 7: /g/, /v/, /a/, /co/, /int/, /sp/, /tv/.

Clover automatically loads the first board in the board list on startup. Instead of always presenting /g/ first it presented one of these /g/, /v/, /a/, /co/, /int/, /sp/, /tv/ (because it was now shuffled). Now I did not put much thought in it, but /a/ isn't the most sfw board there is, even when it's a blue board. So there was a 1 in 7 change of /a/ winding up at the top of the board list and getting automatically loaded. And that was when the fun started. After uploading a new beta version this was probably the case and Clover got suspended. They denied my appeal with the following reason: "Your app depicts images of anime characters in sexually suggestive poses which is considered sexually explicit content." So /a/ was indeed the culprit.

Clover now has more safe boards as default and doesn't automatically add any boards anymore. /a/ and some other boards are now marked as a nsfw boards, so you won't even see a drop down for it.

Now you could say that every browser or reddit app should also be banned from the Play Store because you can browse nsfw material with them. But the problem is that Clover presented /a/ without any searching for nsfw material. It's fine if you make the user search for nsfw material if they know the url/board code/subreddit name, but don't present it without any action.

Even Google Play recommends just uploading a new version with another package name and that's what I'm going to do. It's a shame that I can't update the 260k current users to the new version, but I hope the word will spread of the new package name. I'll give another update when I've uploaded it.

**Comment by benwaffle** [comment] 2016-01-26 16:46
Since your appeal has been denied you cannot upload a fix under the same package name?

**Comment by krt16s** [comment] 2016-01-26 23:59
No, that's how fracked up the play store is...

@floens: If you intend to change the package id, please note that fdroid cannot update existing users, as well. If you really want to go this way, please release a last version with the old package id that explains to the users, that they have to move to another app (a new package id essential is another, unrelated app...).

**Comment by jaibamon** [comment] 2016-01-28 21:30
Floens, how about uploading the app on the Amazon App Store?

**Comment by Floens** [comment] 2016-01-29 13:35
Clover has been re-uploaded to Google Play here:
https://play.google.com/store/apps/details?id=org.floens.clover

I've made two flavors, normal and play. The normal flavor has the package name .chan and play has the package name .clover. I intend to keep the F-Droid package the same, so F-Droid should compile the normal flavor.

@jaibamon I see no benefit to uploading to the Amazon app store right now.

**Comment by DemetriussXVII** [comment] 2016-02-01 16:37
Was it removed again? @Floens

**Comment by Floens** [comment] 2016-02-01 16:42
Clover has been suspended from Google Play again just now.

The reason this time being: "After a regular review, we have determined that your app or app listing links the user to a website with pornographic or sexual content. This violates the Content Policy. Please refer to the Sex and Nudity policy help article for more information."

This basically means that 4chan is just plainly not allowed. Reuploading will be useless because they're after me, so I'm not going to.

Clover will exist in F-Droid, and I recommend you get it from there so you will receive future updates. https://f-droid.org/app/org.floens.chan

**Comment by DemetriussXVII** [comment] 2016-02-01 17:44
@Floens Will they refund you?

**Comment by tw332** [comment] 2016-02-03 20:29
Question - if there are similar apps for similar boards (eg Relay for Reddit and BaconReader for Reddit), are they not subject to the same fate?

**Comment by Xefir** [comment] 2016-02-04 11:31
@tw332 Please re-read the updated disclaimer : http://floens.github.io/Clover/gp_unavailable.txt

@Floens drops and will not upload again on Google Play.

You can switch back to f-droid instead.

**Comment by c933103** [comment] 2016-02-06 08:17
Isn't there a google play content categorization that allow you to say your is mature?

And, When I try to install from F-droid, android tell me that: An existing package by the same name with a conflicting signature is already installed. What's wrong?

and starting from yesterday I can't get captcha loading on the slightly outdated version of clover, is it fixed on the latest version on fdroid?

**Comment by krt16s** [comment] 2016-02-06 11:18
F-Droid packages are signed by a different key (since we build the app from source).

**Comment by zeropi** [comment] 2016-08-20 03:05
i am actually not sure if i have a wrong version or what, but i cant find and add the anime board to my catalog in clover.

**Comment by Floens** [comment] 2016-12-20 10:57
I'm closing this issue for #264

**Closed by Floens** 2016-12-20 10:57 UTC

**Comment by ParkerK** [comment] 2017-06-14 00:32
@Floens - just curious, would marking the app as "Mature" prevent this issue?
