### ISSUE TITLE
Cannot enable pass 2.3.1

### ISSUE THREAD

**Issue by KoenigKrote** [Floens/Clover#427] opened 2018-02-21 17:40 UTC
Attempting to enable 4chan Pass sits on "loading..." for a short bit then returns "Connection Error"
Occurs on both Wifi and Cellular

Android version: 7.0
Phone model: LG G6
Clover version: 2.3.1

**Comment by Floens** [comment] 2018-02-21 17:56
Probably related to #407

**Comment by tidux** [comment] 2018-02-21 21:09
Seeing this same issue.  Android 7, LGV20.

**Comment by tidux** [comment] 2018-02-21 21:19
This issue is fixed in dev.  Time for a backported patch or a new release?

**Comment by Floens** [comment] 2018-02-21 21:19
Are you sure, because that code wasn't changed.

**Comment by tidux** [comment] 2018-02-21 21:22
I have both 2.3.1 and dev installed on the same device.  Signing in with my pass succeeds on dev and fails with "Connection error" on 2.3.1.  Both are github apks.  I've reconfirmed just now.  Signing in via Firefox also works on this device.

**Comment by Floens** [comment] 2018-02-21 21:25
The only thing that is changed is the user agent, because it's based on the current version code. I woudn't know what else there would be to fix.

**Comment by tidux** [comment] 2018-02-21 21:36
Well that's great.  Thanks, (((Cloudflare))).

**Comment by Floens** [comment] 2018-03-05 15:21
Is this still broken?

**Comment by KoenigKrote** [comment] 2018-03-05 16:38
Seems to be resolved, not sure from what

**Closed** 2018-03-08 16:31 UTC
