### ISSUE TITLE
Pinned threads list

### ISSUE THREAD

**Issue by Decme** [Floens/Clover#215] opened 2016-07-14 10:45 UTC
Reposting because the last issue I opened did not give me an opportunity to post the actual issue. I put the issue as a comment afterwards, but the issue was prematurely closed (1 minute? C'mon)

I tend to have a lot of threads pinned. There are 3 major issues with this list though. First, it shows oldest pinned threads at the top, meaning you have to scroll all the way down to reach the latest pinned threads. Second, scrolling is non 'finger sticky' if that makes sense. You can't rapidly flick the list up, you have to painstakingly swipe your finger for each view.

Lastly, your position on the pinned thread list is reset when you accidentally close Clover by pressing the back button one too many times.

**Comment by Floens** [comment] 2016-07-14 10:50
You completely ignored the template so I closed it.

This has been reported in #210

>Second, scrolling is non 'finger sticky' if that makes sense. You can't rapidly flick the list up, you have to painstakingly swipe your finger for each view.

This is the behaviour of the standard RecyclerView swipe to dismiss. IMO this is still flickable. There's not a lot we can do.

>Lastly, your position on the pinned thread list is reset when you accidentally close Clover by pressing the back button one too many times.

Closing by the back button means killing the app, so no state is restored. If you encounter this issue a lot, there's an advanced option that warns before closing the app.

**Comment by Decme** [comment] 2016-07-14 10:58
Of course there was no template, there was nothing at all, because github didn't give me the option to post anything aside from the title. The next box was grayed out.

Android version 5
Samsung Galaxy S4
Clover 1.2.11
These issues aren't really dependant on Android version, phone model, and likely not even Clover version.

Is the advanced option that warns before closing the app available in v 1.2.11?

Also, before anyone brings up the fact that I'm using an old version of Clover... at the moment it's simply better. The catalog view alone in v2 is enough to put me off.

**Comment by Floens** [comment] 2016-07-14 11:04
The template is available on desktop and mobile.
We don't support older versions, obviously. This is why the template is important, issues only matter for the latest version.
I don't know if the advanced option exist. The scrolling behaviour is better in v2.
The only issue left is a duplicate of #210 so I'm closing this issue.

**Closed by Floens** 2016-07-14 11:04 UTC
